version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    environment:
      - DEEP_LYNX_URL=${DEEP_LYNX_URL}
      - DEEP_LYNX_API_KEY=${DEEP_LYNX_API_KEY}
      - DEEP_LYNX_API_SECRET=${DEEP_LYNX_API_SECRET}
      - DEEP_LYNX_CONTAINER_ID=${DEEP_LYNX_CONTAINER_ID}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build:
      context: ./services/frontend
      args:
        - NODE_ENV=production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: 